# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_assessment_num', models.CharField(max_length=20)),
                ('expert_assessment_date', models.DateField()),
                ('stir', models.CharField(max_length=100)),
                ('guarantors_count', models.SmallIntegerField()),
                ('branch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.agroleasingbranch')),
            ],
            options={
                'db_table': 'ExpertAssessment',
            },
        ),
    ]
