# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_assessment', '0001_initial'),
        ('leasing_agreem', '0001_initial'),
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertassessment',
            name='business_plan_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file'),
        ),
        migrations.AddField(
            model_name='expertassessment',
            name='expert_opinion_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file'),
        ),
        migrations.AddField(
            model_name='expertassessment',
            name='financial_stability_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file'),
        ),
        migrations.AddField(
            model_name='expertassessment',
            name='leasing_agreem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing_agreem.leasingagreement'),
        ),
        migrations.AddField(
            model_name='expertassessment',
            name='payment_solvency_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file'),
        ),
    ]
