# Generated by Django 4.0.4 on 2022-06-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('expert_assessment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertassessment',
            name='leasing_agreem',
        ),
        migrations.AddField(
            model_name='expertassessment',
            name='order_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
