# Generated by Django 4.0.4 on 2022-06-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_assessment', '0004_expertassessment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertassessment',
            name='expert_assessment_date',
        ),
        migrations.RemoveField(
            model_name='expertassessment',
            name='expert_assessment_num',
        ),
        migrations.RemoveField(
            model_name='expertassessment',
            name='stir',
        ),
    ]
