# Generated by Django 4.0.4 on 2022-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_assessment', '0006_alter_expertassessment_guarantors_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertassessment',
            name='soato',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
