# Generated by Django 4.0.4 on 2022-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_assessment', '0007_expertassessment_soato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertassessment',
            name='soato',
        ),
    ]
