# Generated by Django 4.0.4 on 2022-06-23 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert_assessment', '0008_remove_expertassessment_soato'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertassessment',
            name='expert_assessment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertassessment',
            name='expert_assessment_num',
            field=models.CharField(default='10/22', max_length=20),
            preserve_default=False,
        ),
    ]
