# Generated by Django 4.0.4 on 2022-06-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_initial'),
        ('expert_assessment', '0009_expertassessment_expert_assessment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertassessment',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.district'),
        ),
    ]
