# Generated by Django 4.0.4 on 2022-05-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.BigIntegerField()),
                ('fullname', models.CharField(max_length=150)),
                ('activity_type', models.TextField()),
                ('organizational_legal_form', models.TextField()),
                ('legal_address', models.TextField()),
                ('postal_code', models.IntegerField()),
                ('home_address', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=20)),
                ('mfo', models.TextField()),
                ('account_num', models.IntegerField()),
                ('bank_name', models.TextField()),
                ('chief_name', models.TextField()),
                ('chief_phone_num', models.CharField(max_length=20)),
                ('accountant_name', models.TextField()),
                ('accountant_phone_num', models.CharField(max_length=20)),
                ('order_num', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('operator', models.CharField(max_length=150)),
                ('branch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.agroleasingbranch')),
                ('technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='technics.technique')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
