# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.BigIntegerField()),
                ('order_num', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('operator', models.CharField(max_length=150)),
                ('branch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.agroleasingbranch')),
                ('technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technics.technique')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
