# Generated by Django 4.0.4 on 2022-06-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_farmerstir'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stir',
        ),
        migrations.AddField(
            model_name='order',
            name='farmer_stir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.farmerstir'),
        ),
    ]
