# Generated by Django 4.0.4 on 2022-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_stir_order_farmer_stir'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='soato',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
