# Generated by Django 4.0.4 on 2022-06-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_initial'),
        ('orders', '0003_order_soato'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.district'),
        ),
    ]
