# Generated by Django 4.0.4 on 2022-06-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_initial'),
        ('orders', '0004_order_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('statement_num', models.CharField(max_length=20)),
                ('statement_type', models.TextField()),
                ('business_plan_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
                ('expert_opinion_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
                ('financial_stability_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('payment_solvency_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
            ],
            options={
                'db_table': 'Statement',
            },
        ),
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futures_contract_num', models.CharField(max_length=20, null=True)),
                ('futures_contract_date', models.DateField(null=True)),
                ('harvest_year', models.IntegerField(null=True)),
                ('type_of_grown_product', models.CharField(max_length=20, null=True)),
                ('contour_of_crop', models.CharField(max_length=20, null=True)),
                ('hectares_of_arable_land', models.IntegerField(null=True)),
                ('financing_percent', models.IntegerField(null=True)),
                ('financing_price', models.BigIntegerField(null=True)),
                ('contract_price', models.BigIntegerField(null=True)),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.statement')),
            ],
            options={
                'db_table': 'FuturesContract',
            },
        ),
        migrations.CreateModel(
            name='ExpertsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jshshir', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.statement')),
            ],
        ),
    ]
