# Generated by Django 4.0.4 on 2022-06-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_statement_futurescontract_expertsstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
