# Generated by Django 4.0.4 on 2022-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_statement_statement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_type',
            field=models.TextField(null=True),
        ),
    ]
