# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing_agreem', '0001_initial'),
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_num', models.CharField(max_length=20)),
                ('guarantee_date', models.DateField()),
                ('lessor_sign', models.CharField(max_length=12, null=True)),
                ('lessee_sign', models.CharField(max_length=12, null=True)),
                ('leasing_agreem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing_agreem.leasingagreement')),
            ],
            options={
                'db_table': 'GuaranteeAgreement',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.CharField(max_length=100)),
                ('guarantor_sign', models.CharField(max_length=12, null=True)),
                ('business_plan_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
                ('expert_opinion_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
                ('financial_stability_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
                ('guarantee_agreem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guarantee_agreem.guaranteeagreement')),
                ('payment_solvency_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files_app.file')),
            ],
            options={
                'db_table': 'Guarantor',
            },
        ),
    ]
