# Generated by Django 4.0.4 on 2022-05-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing_agreem', '0001_initial'),
        ('guarantee_agreem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteeagreement',
            name='leasing_agreem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing_agreem.leasingagreement'),
        ),
    ]
