# Generated by Django 4.0.4 on 2022-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee_agreem', '0002_remove_guarantor_stir'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='stir',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
