# Generated by Django 4.0.4 on 2022-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee_agreem', '0005_guarantor_business_plan_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteeagreement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
