# Generated by Django 4.0.4 on 2022-06-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_farmerstir_accountant_and_more'),
        ('guarantee_agreem', '0006_guaranteeagreement_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='stir',
        ),
        migrations.AddField(
            model_name='guarantor',
            name='farmer_stir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.farmerstir'),
        ),
    ]
