# Generated by Django 4.0.4 on 2022-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee_agreem', '0007_remove_guarantor_stir_guarantor_farmer_stir'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteeagreement',
            name='soato',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
