# Generated by Django 4.0.4 on 2022-06-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee_agreem', '0009_remove_guaranteeagreement_soato'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='payment_obligation',
            field=models.CharField(default='Qisman', max_length=20),
            preserve_default=False,
        ),
    ]
