# Generated by Django 4.0.4 on 2022-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerSTIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=60)),
                ('short_name', models.CharField(max_length=40)),
                ('business_type', models.CharField(max_length=40)),
                ('business_structure', models.CharField(max_length=40)),
                ('legal_address', models.CharField(max_length=200)),
                ('postcode', models.IntegerField()),
                ('home_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('mfo', models.CharField(max_length=20)),
                ('payment_account', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=60)),
                ('director_number', models.CharField(max_length=20)),
                ('accountant', models.CharField(max_length=60)),
                ('accountant_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'FarmerSTIR',
            },
        ),
    ]
