# Generated by Django 4.0.4 on 2022-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_farmerstir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerstir',
            name='accountant',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='accountant_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='business_structure',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='business_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='director',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='director_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='full_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='home_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='legal_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='mfo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='payment_account',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='short_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='stir',
            field=models.BigIntegerField(null=True),
        ),
    ]
