# Generated by Django 4.0.4 on 2022-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_farmerstir_accountant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerstir',
            name='soato',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
