# Generated by Django 4.0.4 on 2022-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_farmerstir_soato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerstir',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerstir',
            name='stir',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
