# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField(unique=True)),
                ('areacode', models.IntegerField()),
                ('areatype', models.TextField(null=True)),
                ('nameru', models.CharField(max_length=60)),
                ('nameuz', models.CharField(max_length=60)),
                ('admincenterru', models.CharField(max_length=30, null=True)),
                ('admincenteruz', models.CharField(max_length=30, null=True)),
                ('isdeleted', models.SmallIntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(unique=True)),
                ('regioncode', models.IntegerField()),
                ('regioncode2', models.IntegerField(null=True)),
                ('nameru', models.CharField(max_length=60)),
                ('nameuz', models.CharField(max_length=60)),
                ('codelat', models.CharField(max_length=2)),
                ('codecyr', models.CharField(max_length=2)),
                ('admincenterru', models.CharField(max_length=30, null=True)),
                ('admincenteruz', models.CharField(max_length=30, null=True)),
                ('isdeleted', models.SmallIntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfy_id', models.IntegerField()),
                ('nameuz', models.CharField(max_length=60, null=True)),
                ('nameru', models.CharField(max_length=60, null=True)),
                ('created_at', models.CharField(max_length=60)),
                ('updated_at', models.CharField(max_length=60)),
                ('district_id', models.ForeignKey(db_column='district_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.district', to_field='district_id')),
                ('region_id', models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', to_field='region_id')),
            ],
            options={
                'db_table': 'MFY',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', to_field='region_id'),
        ),
    ]
