# Generated by Django 4.0.4 on 2022-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfy',
            name='nameru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mfy',
            name='nameuz',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
