# Generated by Django 4.0.4 on 2022-06-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Province',
        ),
        migrations.AlterModelTable(
            name='province',
            table='Province',
        ),
    ]
