# Generated by Django 4.0.4 on 2022-06-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_rename_region_province_alter_province_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfy',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='mfy',
            name='region_id',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='MFY',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
