# Generated by Django 4.0.4 on 2022-06-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_remove_mfy_district_id_remove_mfy_region_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('nameru', models.TextField(null=True)),
                ('district_prefix', models.TextField()),
                ('soato_code', models.TextField(null=True)),
            ],
            options={
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nameru', models.TextField(null=True)),
                ('region_prefix', models.TextField()),
                ('soato_code', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Province',
            },
        ),
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('nameru', models.TextField(null=True)),
                ('mfy_prefix', models.TextField()),
                ('soato_code', models.TextField(null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.district')),
            ],
            options={
                'db_table': 'MFY',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.province'),
        ),
    ]
