# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.CharField(max_length=20, null=True)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('trust_num', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('postal_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_num', models.CharField(max_length=20, null=True)),
                ('act_date', models.DateField(null=True)),
                ('seller_stir', models.CharField(max_length=60, null=True)),
                ('seller_sign', models.CharField(default=None, max_length=12, null=True)),
                ('lessor_sign', models.CharField(default=None, max_length=12, null=True)),
                ('lessee_sign', models.CharField(default=None, max_length=12, null=True)),
                ('detected_defects_header', models.CharField(max_length=40, null=True)),
                ('detected_defects_info', models.TextField(null=True)),
                ('quality_conclusion_header', models.CharField(max_length=40, null=True)),
                ('quality_conclusion_info', models.TextField(null=True)),
                ('branch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.agroleasingbranch')),
            ],
            options={
                'db_table': 'Act',
            },
        ),
    ]
