# Generated by Django 4.0.4 on 2022-05-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing_agreem', '0001_initial'),
        ('acts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='detected_defects_header',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='detected_defects_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='leasing_agreem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing_agreem.leasingagreement'),
        ),
        migrations.AlterField(
            model_name='act',
            name='quality_conclusion_header',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='quality_conclusion_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='seller',
            field=models.CharField(default='APIdan keladi', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='stir',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='trust_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
