# Generated by Django 4.0.4 on 2022-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
