# Generated by Django 4.0.4 on 2022-06-17 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_farmerstir_accountant_and_more'),
        ('acts', '0003_act_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='seller_stir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.farmerstir'),
        ),
    ]
