# Generated by Django 4.0.4 on 2022-05-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_alter_act_act_date_alter_act_act_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='guarantor_sign',
            new_name='seller_sign',
        ),
    ]
