# Generated by Django 4.0.4 on 2022-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0005_act_soato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='soato',
        ),
    ]
