# Generated by Django 4.0.4 on 2022-06-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0006_remove_act_soato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='is_active',
            new_name='is_delivered',
        ),
    ]
