# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('gen_name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('path', models.TextField()),
                ('content_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=30)),
                ('expert_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='expert_assessment.expertassessment')),
            ],
            options={
                'db_table': 'Uploads',
            },
        ),
    ]
