# Generated by Django 4.0.4 on 2022-05-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing_agreem', '0001_initial'),
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment_day', models.CharField(max_length=10)),
                ('delivered_technics_count', models.IntegerField()),
                ('leasing_agreem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing_agreem.leasingagreement')),
                ('technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technics.technique')),
            ],
            options={
                'db_table': 'PaymentGraph',
            },
        ),
    ]
