# Generated by Django 4.0.4 on 2022-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_graph', '0002_remove_paymentgraph_delivered_technics_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgraph',
            name='days_count',
        ),
        migrations.RemoveField(
            model_name='paymentgraph',
            name='last_payment_day',
        ),
        migrations.AddField(
            model_name='paymentgraph',
            name='total_quarterly_lease_term_part_of_value',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgraph',
            name='total_quarterly_lease_term_payment',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgraph',
            name='total_quarterly_percent_lease_term_payment',
            field=models.CharField(default='asd', max_length=20),
            preserve_default=False,
        ),
    ]
