# Generated by Django 4.0.4 on 2022-05-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_graph', '0003_remove_paymentgraph_days_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgraph',
            name='total_quarterly_lease_term_part_of_value',
        ),
        migrations.RemoveField(
            model_name='paymentgraph',
            name='total_quarterly_lease_term_payment',
        ),
        migrations.RemoveField(
            model_name='paymentgraph',
            name='total_quarterly_percent_lease_term_payment',
        ),
    ]
