# Generated by Django 4.0.4 on 2022-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_graph', '0004_paymentgraph_soato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgraph',
            name='soato',
        ),
    ]
