# Generated by Django 4.0.4 on 2022-05-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leasing_num', models.CharField(max_length=20)),
                ('leasing_date', models.DateField()),
                ('contract_price', models.BigIntegerField()),
                ('number_of_techs', models.IntegerField()),
                ('lessor_sign', models.CharField(max_length=12, null=True)),
                ('lessee_sign', models.CharField(max_length=12, null=True)),
                ('guarantor_sign', models.CharField(max_length=12, null=True)),
                ('order_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
            ],
            options={
                'db_table': 'LeasingAgreement',
            },
        ),
    ]
