# Generated by Django 4.0.4 on 2022-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing_agreem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasingagreement',
            name='stir',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
