# Generated by Django 4.0.4 on 2022-05-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('leasing_agreem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingagreement',
            name='order_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
