# Generated by Django 4.0.4 on 2022-06-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_assessment', '0003_remove_expertassessment_leasing_agreem_and_more'),
        ('leasing_agreem', '0002_leasingagreement_stir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasingagreement',
            name='order_model',
        ),
        migrations.AddField(
            model_name='leasingagreement',
            name='expert_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert_assessment.expertassessment'),
        ),
    ]
