# Generated by Django 4.0.4 on 2022-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing_agreem', '0003_remove_leasingagreement_order_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasingagreement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
