# Generated by Django 4.0.4 on 2022-06-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing_agreem', '0004_leasingagreement_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasingagreement',
            name='stir',
        ),
    ]
