# Generated by Django 4.0.4 on 2022-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing_agreem', '0006_leasingagreement_soato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasingagreement',
            name='soato',
        ),
    ]
